-- 코드를 입력하세요
SELECT R1.FOOD_TYPE, R1.REST_ID, R1.REST_NAME, R1.FAVORITES
FROM REST_INFO R1
WHERE (R1.FOOD_TYPE, R1.FAVORITES) IN ( SELECT R.FOOD_TYPE, MAX(R.FAVORITES) FAVORITES
                                        FROM REST_INFO R
                                        GROUP BY R.FOOD_TYPE )
ORDER BY R1.FOOD_TYPE DESC