-- 코드를 입력하세요
SELECT os.USER_ID, os.PRODUCT_ID
FROM ONLINE_SALE os
GROUP BY os.USER_ID, os.PRODUCT_ID
HAVING COUNT(os.PRODUCT_ID) >= 2
ORDER BY os.USER_ID ASC, os.PRODUCT_ID DESC
# SELECT *
# FROM ONLINE_SALE
# WHERE USER_ID = 2