-- 코드를 입력하세요
SELECT ub.WRITER_ID, uf.NICKNAME, SUM(ub.PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD ub INNER JOIN USED_GOODS_USER uf
     ON ub.WRITER_ID = uf.USER_ID
WHERE ub.STATUS = 'DONE'
GROUP BY ub.WRITER_ID
HAVING SUM(ub.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC