-- 코드를 입력하세요
SELECT DATE_FORMAT(os.SALES_DATE,"%Y-%m-%d") SALES_DATE, os.PRODUCT_ID, os.USER_ID, os.SALES_AMOUNT
FROM ONLINE_SALE os
WHERE DATE_FORMAT(os.SALES_DATE,"%Y-%m") = '2022-03'
UNION
SELECT DATE_FORMAT(off.SALES_DATE,"%Y-%m-%d") SALES_DATE, off.PRODUCT_ID, NULL as USER_ID, off.SALES_AMOUNT
FROM OFFLINE_SALE as off
WHERE DATE_FORMAT(off.SALES_DATE,"%Y-%m") = '2022-03'
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC